import type { Metadata } from "next";
import { TikTok_Sans } from "next/font/google";
import "./globals.css";
import { ThemeProvider } from "@/provider/theme-provider";

const tikTokSans = TikTok_Sans({
  subsets: ["latin"],
  weight: ["400", "500", "700"],
  variable: "--font-tiktok-sans",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="vi" suppressHydrationWarning>
      <body className={`${tikTokSans.className}`}>
        <ThemeProvider
          attribute="class"
          defaultTheme="light"
          enableSystem={false}
          disableTransitionOnChange>
          <div className="min-h-screen p-2">{children}</div>
        </ThemeProvider>
      </body>
    </html>
  );
}
